apiVersion: apps/v1
kind: Deployment
metadata:
  name: cit270garyservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cit270garyservice
  template:
    metadata:
      name: cit270garyservice
      labels:
        app: cit270garyservice
    spec:
      containers:
      - name: cit270garyservice
        image: gcr.io/cit-270-kubernetes/gary-api
        volumeMounts: 
        - name: ssl
          mountPath: "/etc/letsencrypt/live/garygaines.cit270.com/"
        command: ["npm"]
        args: ["run","start"]
        resources:
          requests:
            cpu: 0.125
            memory: 500Mi
          limits:
            cpu: 0.125
            memory: 600Mi
        imagePullPolicy: Always
      volumes:
      - name: ssl
        secret: 
          secretName: garycerts